"""add order sync table

Revision ID: 312b195d8e6a
Revises: 00efbdf755de
Create Date: 2025-05-07 06:23:50.045578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312b195d8e6a'
down_revision: Union[str, None] = '00efbdf755de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_role_permission_uc', 'rolepermission', ['role_id', 'permission_id'])
    op.create_unique_constraint('_user_role_uc', 'userrole', ['user_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_role_uc', 'userrole', type_='unique')
    op.drop_constraint('_role_permission_uc', 'rolepermission', type_='unique')
    # ### end Alembic commands ###
